### ISSUE TITLE
[Feature Request] Split --all-formats into --all-audio-formats and --all-video-formats

### ISSUE THREAD

**Issue by werid** [pukkandan/yt-dlp#101]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.02.19**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

The --all-formats description says it will download all _video_ formats, but actually downloads all audio and video formats. My request is to split it up into two new arguments, so you can actually download all audio or video formats, while keeping --all-formats to download everything.

I want to grab all audio from some (unsupported) sites with multiple audio streams (different languages), but i don't need more than one video format, but the format codes used aren't consistent.

**Comment by pukkandan** [comment]
I was looking for how easy this is to implement. Then I found that this feature actually already exists, but is undocumented. You can use `all` in the format selector.

> I want to grab all audio from some (unsupported) sites with multiple audio streams (different languages), but i don't need more than one video format, but the format codes used aren't consistent.

So for this, you can do `-f all[vcodec=none]`

Note that `allvideo`/`allaudio` doesn't work

I will make sure to properly document this

**Comment by werid** [comment]
Oh, a clever trick. This works great, you can even get video in one command by doing ```-f "all[vcodec=none],bestvideo"``` 

Thanks!

**Comment by pukkandan** [comment]
Yes, and since you can use any filter with it it is much more flexible than your original proposal
