### ISSUE TITLE
[Broken] Roosterteeth.com Subtitles

### ISSUE THREAD

**Issue by czarchasm00** [pukkandan/yt-dlp#15]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2021.01.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Windows\system32>python3 -m pip install git+https://github.com/pukkandan/yt-dlc
Collecting git+https://github.com/pukkandan/yt-dlc
  Cloning https://github.com/pukkandan/yt-dlc to c:\users\czarch~1\appdata\local\temp\pip-req-build-w5qsaker
Using legacy 'setup.py install' for youtube-dlc, since package 'wheel' is not installed.
Installing collected packages: youtube-dlc
    Running setup.py install for youtube-dlc ... done
Successfully installed youtube-dlc-2021.1.10

C:\Windows\system32>youtube-dlc -v https://roosterteeth.com/watch/rwby-season-1-episode-1 --list-subs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://roosterteeth.com/watch/rwby-season-1-episode-1', '--list-subs']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2021.01.10
[debug] Python version 3.7.9 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[RoosterTeeth] rwby-season-1-episode-1: Downloading video JSON metadata
[RoosterTeeth] rwby-season-1-episode-1: Downloading m3u8 information
[debug] Sort order given by user:
[debug] Formats sorted by: has_video, quality, extractor_preference, language_preference, dimension, fps, vcodec, acodec, filesize, filesize_approx, tbr, vbr, abr, asr, protocol, vext, aext, has_audio, source_preference, format_id
[RoosterTeeth] rwby-season-1-episode-1: Downloading episode JSON metadata
16024 has no subtitles

C:\Windows\system32>youtube-dlc --version
2021.01.10
```

## Description

youtube-dlc does not recognize subtitles on roosterteeth.com.
Links that were tested:
- https://roosterteeth.com/watch/rwby-season-1-episode-1
- https://roosterteeth.com/watch/rwby-season-1-episode-2
- https://roosterteeth.com/watch/rwby-season-1-episode-3
- https://roosterteeth.com/watch/rwby-season-1-episode-4
- https://roosterteeth.com/watch/gary-and-his-demons-season-1-still-the-one

I am able to load all the subtitles using the built-in player, so this is a youtube-dlc issue.

**Comment by pukkandan** [comment]
The issue exists in [youtube-dl](https://github.com/ytdl-org/youtube-dl) as well. Could you also make an issue report either there or in [dlc](https://github.com/blackjack4494/youtube-dlc)?. That way we will probably have more people working on a solution. This fork is being watched by only a very small number of devs

**Comment by czarchasm00** [comment]
It's already been reported in [this issue](https://github.com/ytdl-org/youtube-dl/issues/25415) on youtube-dl. It has been mostly ignored, even though I have updated it several times and continue to with every new version.

**Comment by pukkandan** [comment]
I wouldn't say blackjack/yt-dlc is dead. Blackjack hasnt been seen for a few months, but there is still a lot of people (including me) watching that repo. So if you post an issue there and someone makes a patch, I will merge it here.

Anyway, I see that there is a PR for this on https://github.com/ytdl-org/youtube-dl/pull/23985 . I will test and merge it if it works correctly

**Comment by czarchasm00** [comment]
Thanks for doing that. I never noticed that pull request, and should've looked.
Be sure to update the installation guide as well now that you have changed the name of the fork.

**Comment by pukkandan** [comment]
oh, thanks. I forgot about that.
