### ISSUE TITLE
[Broken] Roosterteeth.com; Some specific videos will not download

### ISSUE THREAD

**Issue by czarchasm00** [pukkandan/yt-dlp#16]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.01.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Windows\system32>youtube-dlc https://roosterteeth.com/watch/rwby-rwby-watch-party -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://roosterteeth.com/watch/rwby-rwby-watch-party', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.12
[debug] Python version 3.7.9 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[RoosterTeeth] rwby-rwby-watch-party: Downloading video JSON metadata
[RoosterTeeth] rwby-rwby-watch-party: Downloading m3u8 information
[debug] Sort order given by user:
[debug] Formats sorted by: has_video, quality, extractor_preference, language_preference, dimension, fps, vcodec, acodec, filesize, filesize_approx, tbr, vbr, abr, asr, protocol, vext, aext, has_audio, source_preference, format_id
[RoosterTeeth] rwby-rwby-watch-party: Downloading episode JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/pukkandan/yt-dlc . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "C:\Users\czarchasm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\youtube_dlc\extractor\common.py", line 633, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\czarchasm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\youtube_dlc\YoutubeDL.py", line 2514, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Specific videos (notably, seemingly all those that appear in the Bonus Features section in https://roosterteeth.com/series/rwby) do not download through youtube-dlp.
Tested videos:
- https://roosterteeth.com/watch/rwby-bonus-18
- https://roosterteeth.com/watch/rwby-volume-7-intro
- https://roosterteeth.com/watch/rwby-rwby-watch-party
- https://roosterteeth.com/watch/rwby-live-from-remnant
-  https://roosterteeth.com/watch/rwby-frwby

All of these videos produce the same errors in youtube-dlp.

## Potential Solution

[This pull request](https://github.com/ytdl-org/youtube-dl/pull/23708) seems like it may be a fix to the issue. Using the pull request's example links, I am getting the same exact errors.

**Comment by pukkandan** [comment]
@Zocker1999NET In PR https://github.com/ytdl-org/youtube-dl/pull/23708, you have changed `episodes` to `watch` in the API url. Are you sure it doesn't break some other URL?

**Comment by Zocker1999NET** [comment]
> @Zocker1999NET In PR [ytdl-org/youtube-dl#23708](https://github.com/ytdl-org/youtube-dl/pull/23708), you have changed `episodes` to `watch` in the API url. Are you sure it doesn't break some other URL?

@pukkandan I don't understand your question in this context. This [PR](https://github.com/ytdl-org/youtube-dl/pull/23708) was not merged yet and I've currently tested the [first URL here](https://roosterteeth.com/watch/rwby-bonus-18), which works with the youtube-dl version with my PR but does not work with the latest release.

In general, I hope the PR will not break any other URLs currently working, otherwise I hope those will be added to the test sequence, so that it will ensured those will also work in the future.

**Comment by pukkandan** [comment]
@Zocker1999NET I know that the PR was not merged. I am looking to merge it in this fork. Hence the question
