### ISSUE TITLE
[Feature Request] Portable configuration files

### ISSUE THREAD

**Issue by pukkandan** [pukkandan/yt-dlp#19]
Hi, @shakir-timur, I am looking to merge your PR https://github.com/ytdl-org/youtube-dl/pull/27592 into this fork.

However, some changes are needed before it can be merged.

1. The portable configuration should be loaded in addition to the user configuration, not as a replacement
2. When running directly from source (Eg: `C:\Progs\yt-dlp\youtube-dlc\__main__.py`), it should **only** look in the module directory (`C:\Progs\yt-dlp\youtube-dlc.conf`)
3. Similarly, when packaged (Eg: `C:\Progs\yt-dlp\youtube-dlc.exe`), it should look only in the root directory (`C:\Progs\yt-dlp\youtube-dlc.conf`)
4. The .conf file name should be changed to `youtube-dlc`, not `youtube-dl`
5. Relevent changes to readme must be made in accordance with these changes

I would appreciate if you could make these changes and make a PR here. 

If you are not interested in implementing the feature in this fork, please ignore this post. I will make the changes myself when I get enough free time.

**Comment by shakir-timur** [comment]
> I would appreciate if you could make these changes and make a PR here.
> 
> If you are not interested in implementing the feature in this fork, please ignore this post. I will make the changes myself when I get enough free time.

Hi, @pukkandan, would like to help, but I'm afraid my acquaintance with python ends there.

**Comment by pukkandan** [comment]
ok, np
