### ISSUE TITLE
[Site Request] trovo.live

### ISSUE THREAD

**Issue by GUUser91** [pukkandan/yt-dlp#20]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.01.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
https://trovo.live/video/ltv-100759829_100759829_1610625308?ltab=videos
https://trovo.live/video/ltv-100499796_100499796_1610389719?ltab=videos

## Description

It's a video game streaming website like Twitch.

**Comment by pukkandan** [comment]
Related: https://github.com/blackjack4494/yt-dlc/issues/220 https://github.com/ytdl-org/youtube-dl/issues/26125

**Comment by pukkandan** [comment]
I have written an extractor for VODs. But since it doesn't support playlists, live vids etc, I am keeping this issue open

**Comment by pukkandan** [comment]
The full extractor has been merged from youtube-dl
