### ISSUE TITLE
MKV thumbnails get embedded with the full original path, instead of just "cover.jpg"

### ISSUE THREAD

**Issue by maaldheefee** [pukkandan/yt-dlp#22]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.01.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

Embedded MKV thumbnails get saved with the full original path as file name, instead of just `cover.jpg`. So it's not shown in the explorer.

For example, when I open such a file with MKVToolNix's Header editor, it says the file name of the attachment is: `d:\downloads\youtube-dl\cover.jpg`.

I use the following config options
--add-metadata
--embed-thumbnail
--merge-output-format mkv
--prefer-ffmpeg

**Comment by pukkandan** [comment]
There was an issue where mkv embedding fails when multiple instances of dlc is run or when `-o` points to a different volume. This issue came from the patch for that issue. 

I am not well versed in how embedded metadata is handled. Does the name strictly have to be `cover.jpg` without any path? Does this issue exist only for mkv?

**Comment by maaldheefee** [comment]
It has to be `cover.jpg` or `.png`

https://www.matroska.org/technical/attachments.html#cover-art

https://github.com/pukkandan/yt-dlp/blob/d7e0c6da7cf100746f5dcc11bc73c663fe76e25e/youtube_dlc/postprocessor/embedthumbnail.py#L101

Adding the following to the end of the list works for me
```
'-metadata:s:t', 'filename=cover.jpg'
```

**Comment by pukkandan** [comment]
Thanks, I will apply that fix asap

**Comment by pukkandan** [comment]
@maaldheefee While editing this, I realized the embedding code is unnecessarily complicated. I have pushed a patch. 

I have an app that extracts thumbnail directly from the video, so it works for me even without this patch
Can you test it and let me know if the cover appears correctly?

**Comment by maaldheefee** [comment]
Works perfectly.

> I have an app that extracts thumbnail directly from the video

I also use such an app, but I want the custom thumbnails in YouTube videos.
