### ISSUE TITLE
[Site Request] audius.co

### ISSUE THREAD

**Issue by Arynthesizer** [pukkandan/yt-dlp#40]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Single tracks: https://audius.co/sanjaux/descent-222909
https://audius.co/naskoedm/where-i-belong-239874
Playlist: https://audius.co/itsvincent_/playlist/sunrise-series-7588

## Description

Audius is a Soundcloud competitor with 320kbps music streaming. 

There is already a functional extractor for audius, but it was never merged, I've been adding it manually and rebuilding yt-dlp with every update but maybe it can be officially added? Thanks for your efforts on this project :)
https://github.com/ytdl-org/youtube-dl/pull/27360/files

**Comment by pukkandan** [comment]
There is an issue with the "valid URLs" of the PR that could cause issue with Generic extractor (or others in the future). https://github.com/ytdl-org/youtube-dl/pull/27360#issuecomment-757123708

> The problem is that I have no idea how handle all of this different hosts with regexp. For now, as a temporary solution, i used .+/v1/tracks regexp, but then this extractor will triggered to links like https://super-random-host.com/v1/tracks/trackID. For now such links do not overlap with other extractors, but who knows what will happen next.

I will look into how to fix this issue, and assuming I can figure out a fix, I will merge it

**Comment by Arynthesizer** [comment]
Thanks again, i really appreciate it!

**Comment by Arynthesizer** [comment]
Hey, I'm not sure whether to leave a new issue but attempting to dl in version 2021.01.29 is throwing an error for me.

C:\ytdl>youtube-dlc -v https://audius.co/disguised/nullboy-false-past-230539
[debug] Command-line config: ['-v', 'https://audius.co/disguised/nullboy-false-past-230539']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.29
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
ERROR: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 950, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 533, in extract
    ie_result = self._real_extract(url)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\audius.py", line 127, in _real_extract
    uploader, title, track_id = mobj.groups()
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by pukkandan** [comment]
It was a mistake I made while merging. Should be fixed now. Can you check with master branch?

```
$youtube-dlc -v https://audius.co/disguised/nullboy-false-past-230539
[debug] Command-line config: ['-v', 'https://audius.co/disguised/nullboy-false-past-230539']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.29
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: c55256c5a
[debug] Python version 3.8.4 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[Audius] Requesting available API hosts
[Audius] nullboy-false-past-230539: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) 0
[debug] Invoking downloader on 'https://audius-discovery.nz.modulational.com/v1/tracks/oGvgX/stream'
[download] Destination: Nullboy - False Past [oGvgX].mp3
[download]  10.3% of 9.67MiB at 766.01KiB/s ETA 00:11
ERROR: Interrupted by user
```

**Comment by ValZapod** [comment]
It only downloads low quality mp3, aac in mp4 that have even higher bitrate: 348 kb/s cannot be downloaded.

**Comment by hsn10** [comment]
audius.co has private ipfs network. They are open source, there will be somewhere written key which is needed for stock ipfs client to join network.
