### ISSUE TITLE
[Question] Subtitle vs Auto-Subtitle vs Live Chat

### ISSUE THREAD

**Issue by undaunt** [pukkandan/yt-dlp#57]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I've been digging reddit and the docs around trying to get this straight in my head. Can you let me know if this is correct?

- If I want to download an external subtitle file, then `--write-subs`
- Ditto the above, but for youtube auto subs, `--write-auto-subs`

Here is where I'm confused. If I want to prefer english, and prefer SRT, but still download whatever is available as a fallback, how do I do that? A combination of `--sub-format "srt/best"` and `--sub-lang en` and `--all-subs` ?

Also, how can I download subs but exclude live_chat JSON files, if possible?

Lastly, is it possible to download auto subs only if regular subs don't exist? Or does it always download both? I'm trying to prefer native subs over auto, and only keep 1.

Ideal scenario: Download english srt subs externally, and embed them into mkv. If there is live chat, ignore. If there are only non-english, grab all instead of english. (If I can't grab all only in that scenario, happy to grab all all the time instead of just english). If there are only auto subs, grab those, but if both exist, ignore the auto subs. Is this possible?

I also was confused testing --list-subs as I saw a lot of languages available for automatic captions on Youtube, but none are srt - I saw vtt, ttml, srv3, srv2, srv1, and json3. I'm assuming the 'best' version of those would get pulled if there is no srt?

Thanks!

**Comment by pukkandan** [comment]
--write-subs --sub-lang en --write-auto-subs --sub-format "srt/best" --convert-subs srt

will download one english subtitle, preferring non-auto generated ones and convert it to `srt`. The `--sub-format "srt/best"` is useless for youtube since youtube does not store the subtitles in srt format. But for other websites, it will try to give preference to srt subs

Does that answer all your questions?

**Comment by undaunt** [comment]
I think so. Since my main goal is to simply archive my favorite youtube content, I'll drop the srt/best and go with the following.

```
--add-metadata
--write-info-json
--write-thumbnail
--write-subs
--sub-lang en
--write-auto-subs
--convert-subs srt
--embed-subs
```

This should download, and embed subs as you described I believe, plus download thumbnail and download/embed metadata? Lastly, can I embed thumbnail into mkv as I'm forcing that as my output format with the native program or do I need an external processor? (I can open a new question for this if we don't want to go off topic.)

Thank you.

**Comment by pukkandan** [comment]
> This should download, and embed subs as you described I believe, plus download thumbnail and download/embed metadata? 

Yes

> can I embed thumbnail into mkv as I'm forcing that as my output format with the native program or do I need an external processor

`--embed-thumbnail` works as long as you have ffmpeg

**Comment by undaunt** [comment]
Thanks!

Is it possible to keep the subtitles post-merger similar to the thumbnail without passing -k? I don't want to keep the intermediate webm and mp4 streams but I do want external subs as well as embedded.

If this isn't possible I'll just keep the subs external.

Thanks again.

**Comment by pukkandan** [comment]
The subtitles should actually be kept (similar to thumbnail). If it doesn't it is a bug. I will look into it

**Comment by pukkandan** [comment]
> Is it possible to keep the subtitles post-merger similar to the thumbnail without passing -k

Fixed

**Comment by undaunt** [comment]
Looks awesome, thanks again for your help.
