### ISSUE TITLE
Installs empty directories etc/bash_completion.d, etc/fish/completions, share/doc/youtube_dlc, share/man/man1

### ISSUE THREAD

**Issue by yurivict** [pukkandan/yt-dlp#59]
Version: 2021.02.04
FreeBSD 12.2
Python-3.7

**Comment by pukkandan** [comment]
How did you install it?

**Comment by yurivict** [comment]
I installed it using ```setup.py install```.

**Comment by pukkandan** [comment]
If you are manually using setup.py, you need to first create the necessary files using either `make all` or `make youtube-dlc man`

**Comment by yurivict** [comment]
> If you are manually using setup.py, you need to first create the necessary files using either make all or make youtube-dlc man

I am not using it manually, I build it in the FreeBSD ports framework. It is in virtually all cases building python ports without the need for any manual steps like this.

**Comment by pukkandan** [comment]
The same "issue" should exist for youtube-dl, no?

The manpages are related files are automatically built for this project and not committed into the repo. That's why it is necessary to run `make`.

Let me see if youtube-dl behaves differently. If it does, I will look into fixing it

**Comment by yurivict** [comment]
Maybe this is common for YouTube downloaders, but other packages manage to do all of this just from ```setup.py```.
