### ISSUE TITLE
Building with pyinst.py on Windows broken since e38df8f

### ISSUE THREAD

**Issue by Jules-A** [pukkandan/yt-dlp#63]
- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.02.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Description

Since https://github.com/pukkandan/yt-dlp/commit/e38df8f9fa4d715513453928591346f680dbe298 building with pyinst is broken on Windows. It appears to be due to moving pyinst.py to devscripts (which I'm not a fan of) as the first error it stops at is: 
```
20983 INFO: Copying icons from ['devscripts\\cloud.ico']
Unable to open icon file devscripts\cloud.ico
```

Pulling it from current directory continues the build (I'm not sure if anything is really broken by it) but doesn't include the metadata and gives this error: 

```
Traceback (most recent call last):
  File "C:\Users\User\Downloads\yt-dlp-master\devscripts\pyinst.py", line 79, in <module>
    SetVersion('dist/youtube-dlc%s.exe' % _x86, VERSION_FILE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 635, in SetVersion
    pe = pefile.PE(exenm, fast_load=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pefile.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pefile.py", line 1797, in __parse__
    stat = os.stat(fname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dist/youtube-dlc.exe'
```

**Comment by pukkandan** [comment]
I am moving pyinst back to the root dir. When it is inside devscripts, everything works as long as you run it from the root-dir. But there are too many things that needs fixing for it to work correctly when run with cd in devscripts.

Where do you think I should put the icon `cloud.ico`?
