### ISSUE TITLE
[YouTube] tab extractor doesn't extract all pages sometimes

### ISSUE THREAD

**Issue by undaunt** [pukkandan/yt-dlp#65]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.02.04**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Custom config file: /mnt/storage/config/yt-dlc-playlists.conf
[debug] Custom config: ['--download-archive', '$MEDIADIR/youtube/archive.log', '--force-ipv4', '--ignore-errors', '--no-continue', '--no-overwrites', '--sleep-interval', '1', '--max-sleep-interval', '10', '--add-metadata', '--write-info-json', '--write-thumbnail', '--write-subs', '--sub-lang', 'en', '--write-auto-subs', '--convert-subs', 'srt', '--embed-subs', '--match-filter', "playlist_title != 'Liked videos' & playlist_title != 'Favorites'", '--format-sort', 'res,fps,vcodec,asr,acodec', '--merge-output-format', 'mkv', '--output', '$MEDIADIR/youtube/%(playlist_uploader)s - %(playlist_title)s - [%(playlist_id)s]/%(playlist_title)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s', '--output', 'pl_infojson:$MEDIADIR/media/youtube/%(playlist_uploader)s - %(playlist_title)s - [%(playlist_id)s]/%(playlist_title)s - Playlist Info.%(ext)s']
[debug] Command-line config: ['--config-location', '/mnt/storage/config/yt-dlc-playlists.conf', 'https://www.youtube.com/playlist?list=PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW', '-v']
[debug] Loading archive file '/mnt/storage/media/youtube/archive.log'
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.02.04
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-65-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW: Downloading webpage
[download] Downloading playlist: Dead Suns Character Intros
[info] Playlist metadata is already present
[youtube:tab] playlist Dead Suns Character Intros: Downloading 5 videos
[download] Downloading video 1 of 5
[youtube] tO68f7aiwOA: Downloading webpage
[debug] Sort order given by user: res,fps,vcodec,asr,acodec
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec, asr, acodec, filesize, fs_approx, tbr, vbr, abr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] Downloading format(s) 22
[info] Writing video subtitles to: /mnt/storage/media/youtube/The Glass Cannon Network - Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW]/Dead Suns Character Intros - S01E1 - Dead Suns Character Introduction with Troy and Matthew [tO68f7aiwOA].en.vtt
[debug] Invoking downloader on 'https://www.youtube.com/api/timedtext?v=tO68f7aiwOA&asr_langs=de%2Cen%2Ces%2Cfr%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru&caps=asr&exp=xftt&xoaf=4&hl=en&ip=0.0.0.0&ipbits=0&expire=1612855317&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=DCE75BB005495597935F5D9F592520006320390B.74A05B56E62C01E03464E53F9EA17DFD57AB0D0E&key=yt8&kind=asr&lang=en&tlang=en&fmt=vtt'
[download] Destination: /mnt/storage/media/youtube/The Glass Cannon Network - Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW]/Dead Suns Character Intros - S01E1 - Dead Suns Character Introduction with Troy and Matthew [tO68f7aiwOA].en.vtt
[download] 100% of 65.64KiB in 00:00
[info] Writing video metadata as JSON to: /mnt/storage/media/youtube/The Glass Cannon Network - Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW]/Dead Suns Character Intros - S01E1 - Dead Suns Character Introduction with Troy and Matthew [tO68f7aiwOA].info.json
[youtube] tO68f7aiwOA: Downloading thumbnail ...
[youtube] tO68f7aiwOA: Writing thumbnail to: /mnt/storage/media/youtube/The Glass Cannon Network - Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW]/Dead Suns Character Intros - S01E1 - Dead Suns Character Introduction with Troy and Matthew [tO68f7aiwOA].webp
[debug] Invoking downloader on 'https://r4---sn-n4v7sney.googlevideo.com/videoplayback?expire=1612851717&ei=pdUhYLXVJ4qQkgaa96ioBw&ip=71.202.121.94&id=o-AHl9o8DW0sPybsNOg7TvEjMQxT7g6FLvnAc9t2wf3APG&itag=22&source=youtube&requiressl=yes&mh=9-&mm=31%2C26&mn=sn-n4v7sney%2Csn-a5meknle&ms=au%2Conr&mv=m&mvi=4&pl=22&initcwndbps=2001250&vprv=1&mime=video%2Fmp4&ns=frr5GW9-8zZ9Q9ssY7IszzAF&cnr=14&ratebypass=yes&dur=481.326&lmt=1524084054337207&mt=1612829325&fvip=4&c=WEB&n=5vjiIId7aguGVYd&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgDrJjLDJI41e1C7yr2nExgPqsSrVFiySnAjQxdWV32hcCIADcfeY454XiQptOYSl5cotLOL04qbl7oWb60uxkwkt_&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPvIV84ycEg0XTjvFPiVnUhvLOzDTmmWcBotPX6gbl8kCIQCSM0wt3NOCT-UtBsNwoKNMFsfuSaQqnPL6Kz6-ds6qHg%3D%3D'
[download] Sleeping 9.08 seconds...
[download] Destination: /mnt/storage/media/youtube/The Glass Cannon Network - Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW]/Dead Suns Character Intros - S01E1 - Dead Suns Character Introduction with Troy and Matthew [tO68f7aiwOA].mp4
[download] 100% of 42.52MiB in 00:03
[Metadata] Adding metadata to '/mnt/storage/media/youtube/The Glass Cannon Network - Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW]/Dead Suns Character Intros - S01E1 - Dead Suns Character Introduction with Troy and Matthew [tO68f7aiwOA].mp4'
```

## Description

I was just clearing out my media location to test due to my recent updates and our back and forth chat on some other items. However, I'm seeing two different issues now upon attempt to redownload.

First, as shown above via the logs - with a completely empty download location and unpopulated archive.log, the program is stating that the playlist JSON metadata file already exists. This is preventing me from subsequently scraping that file for various metadata info and curling the thumbnail image. I can't figure out how that's happening with a net new/clear download location.

Second, not pictured above, but if I kick off a full channel or playlist download, sometimes it limits the number of playlists or videos to 30. My channel I've been testing with, `https://www.youtube.com/c/TheGlassCannon/playlists` - has 34 playlists, and 13 pages of videos (including those within playlists).

However, sometimes when downloading it'll only scrape a random 30 of the 34 playlists, or the first 30 videos and not iterate through all pages. I can't find an error on this without debug on but I presume it's some kind of rate limiting? I'm wondering if you had seen it before.

Thanks!

Edit: This appears to only be happening with /playlist URL downloads, not channel or /video URLs. I was able to download a brand new channel I've never grabbed before (NFL)'s channel playlist, but not the playlist ones, and my favorite test channel also worked channel side but not playlist side.

**Comment by pukkandan** [comment]
> with a completely empty download location and unpopulated archive.log, the program is stating that the playlist JSON metadata file already exists. 

I can't reproduce this issue. Please confirm that the file does not exist

    $MEDIADIR/media/youtube/The Glass Cannon Network - Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW] /Dead Suns Character Intros - Playlist Info.info.json

Note: I noticed that your video output points to `$MEDIADIR/youtube` and not `$MEDIADIR/media/youtube/`

> Second, not pictured above, but if I kick off a full channel or playlist download, sometimes it limits the number of playlists or videos to 30. 

I didn't test this, but probably an issue with youtube page continuations. It will take a bit of time for me to fully debug and fix it. I'll get to it tonight/tomorrow

**Comment by pukkandan** [comment]
Same issue as https://github.com/ytdl-org/youtube-dl/issues/28075 https://github.com/ytdl-org/youtube-dl/issues/27981#issuecomment-773239095

**Comment by undaunt** [comment]
@pukkandan Ugh, so infuriating I missed that. Yes, bad path only on one of the four paths across two config files. Thank you.

Re: the other issue, sounds good - should we close this then and just watch that since it is upstream?

Thanks very much.

**Comment by pukkandan** [comment]
No, I'm almost done with it. Testing now

**Comment by pukkandan** [comment]
Should be fixed now @undaunt 
Btw, next time when you have 2 unrelated problems, please open 2 separate issues
