### ISSUE TITLE
[Bug] Thumbnail embed/write behavior

### ISSUE THREAD

**Issue by undaunt** [pukkandan/yt-dlp#67]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.02.04**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

There is an existing issue for this on yt-dl that isn't getting much traction, wasn't sure if it was more appropriate to mention you there or post it here - sorry if this is incorrect.

https://github.com/ytdl-org/youtube-dl/issues/27041

> It is definitely a bug.
> 
> * with `--write-thumbnail` only: the original .webp file is written
> * with `--embed-thumbnail` only: the original .webp file is converted to lossy jpeg, embedded into the media file, then deleted.
> * with **both** options at the same time: the original .webp file is lost, and only the converted .jpg file remains there.
> 
> Using the `--embed-thumbnail` changes the meaning of the `--write-thumbnail` and causes data loss.
> 
> There is an other bug, the `--embed-thumbnail` does not keep the media file's mtime and changes it to the current timestamp. This is inconsistent because the other embed options keep the mtime.

**Comment by pukkandan** [comment]
Never mention yt-dlp in the original repo. They will just remove the comment and if you repeat, you'll get banned

> There is an other bug, the --embed-thumbnail does not keep the media file's mtime and changes it to the current timestamp. This is inconsistent because the other embed options keep the mtime.

No idea how to fix this

I'll fix the rest

**Comment by undaunt** [comment]
Thanks very much!

**Comment by pukkandan** [comment]
Give me an example video to test

**Comment by undaunt** [comment]
This playlist of 5 videos are each less than 10 minutes, all of them downloaded webp for me with write on, but with both on left me with jpg.

https://www.youtube.com/playlist?list=PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW

**Comment by pukkandan** [comment]
> There is an other bug, the --embed-thumbnail does not keep the media file's mtime and changes it to the current timestamp. This is inconsistent because the other embed options keep the mtime.

Fixed
