### ISSUE TITLE
niconico missing metadata

### ISSUE THREAD

**Issue by rivke41levp656** [pukkandan/yt-dlp#77]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.02.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

On newest commit, uploader name from niconico channels is not fetched. Niconico has 2 types of uploaders: 
`https://www.nicovideo.jp/user/number` and
`https://ch.nicovideo.jp/channelname`

It seems uploads from the 2nd type fail.
For example output templates `"%(uploader)s.%(ext)s"` and `"%(channel)s.%(ext)s"` produce `NA.mp4` for videos from https://ch.nicovideo.jp/anitama-ch

**Comment by pukkandan** [comment]
@bbepis @tsukumijima @tsukumi Could one of you have a look

**Comment by kurumigi** [comment]
Send PR #90 to fix it.
