### ISSUE TITLE
[Broken] Viki Error 403 Forbidden and Error 404 Not Found

### ISSUE THREAD

**Issue by shivsah** [pukkandan/yt-dlp#91]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.02.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

Verbose output when using headers..
```
[debug] Command-line config: ['-F', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', '--add-header', 'x-viki-app-ver: 2.2.5.1428709186', '--add-header', 'x-viki-as-id: 100005a', 'https://www.viki.com/videos/1143941v-the-fiery-priest-episode-1']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.02.15
[debug] Python version 3.7.3 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2753, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```
Verbose without the added headers..
```
[debug] Command-line config: ['-F', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', 'https://www.viki.com/videos/1143941v-the-fiery-priest-episode-1']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.02.15
[debug] Python version 3.7.3 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2753, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

I've tried passing the headers and tried passing without the headers to no avail..

Has anyone got any solution to this..?

@pukkandan

**Comment by shivsah** [comment]
as @zackmark29 answered

x-viki-app-ver : 6.0.0
x-client-user-agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36

should be the one used..

**Comment by zackmark29** [comment]
> as @zackmark29 answered
> 
> ```
> x-viki-app-ver : 6.0.0
> x-client-user-agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
> ```
> 
> should be the one used..
> 
> ```
> [debug] Command-line config: ['-F', '--username', 'PRIVATE', '--password', 'PRIVATE', '--add-header', 'x-viki-app-ver:6.0.0', '--add-header', 'x-viki-as-id: 100005a', '--add-header', 'x-client-user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36', '--sub-lang', 'en', '--sub-format', 'vtt', '--write-sub', 'https://www.viki.com/videos/1176905v-river-where-the-moon-rises-episode-1', '--verbose']
> [debug] Loading archive file None
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] yt-dlp version 2021.02.15
> [debug] Python version 3.7.3 (CPython 64bit) - Windows-10-10.0.19041-SP0
> [debug] exe versions: ffmpeg 4.2, ffprobe 4.2
> [debug] Proxy map: {}
> [viki] Logging in
> [viki] 1176905v: Downloading video JSON
> [viki] 1176905v: Downloading new video JSON to get subtitles
> [viki] 1176905v: Downloading MPD manifest
> WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
> [viki] 1176905v: Downloading video streams JSON
> [viki] 1176905v: Downloading MPD manifest
> WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
> [debug] Sort order given by user:
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [info] Available formats for 1176905v:
> ID         EXT RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
> ---------- --- ---------- --- - ----- ----- - ----------- ----- --------- ---- ------- ------------------------------------
> mpd-http-6 m4a audio only     |   63k https |                   mp4a.40.2  63k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
> mpd-http-7 m4a audio only     |   79k https |                   mp4a.40.2  79k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
> mpd-http-5 m4a audio only     |  191k https |                   mp4a.40.2 191k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
> mpd-http-8 m4a audio only     |  191k https |                   mp4a.40.2 191k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
> mpd-http-1 mp4 426x238    30  |  191k https | avc1.640015  191k                        DASH video, mp4_dash
> mpd-http-2 mp4 640x360    30  |  356k https | avc1.64001E  356k                        DASH video, mp4_dash
> mpd-http-3 mp4 852x480    30  |  556k https | avc1.64001F  556k                        DASH video, mp4_dash
> mpd-http-4 mp4 1280x720   30  | 1062k https | avc1.64001F 1062k                        DASH video, mp4_dash
> ```

That's great!

**Comment by shivsah** [comment]
Now we only need a way around that DRM protection.. 😅😅

**Comment by pukkandan** [comment]
This shouldn't have been closed since the issue is not actually fixed. Passing headers is just a workaround


> Now we only need a way around that DRM protection..

This will never be officially supported. You can download the stream using `--allow-unplayable-formats`. What you do with it is up to you

**Comment by zackmark29** [comment]
> Now we only need a way around that DRM protection.. 😅😅



> Now we only need a way around that DRM protection.. 😅😅

haha this? 
![image](https://user-images.githubusercontent.com/62680932/108375813-4b7d3380-723d-11eb-94fb-c351729fe344.png)
But it's only my private tool so you can't find it anywhere :)

**Comment by shivsah** [comment]
> This shouldn't have been closed since the issue is not actually fixed. Passing headers is just a workaround
> 
> > Now we only need a way around that DRM protection..
> 
> This will never be officially supported. You can download the stream using `--allow-unplayable-formats`. What you do with it is up to you

😅😅 This actually ends up removing some formats..

**Comment by pukkandan** [comment]
@zackmark29 I am removing ur comment. I don't want this repo to get in any trouble

@shivsah That shouldn't happen. Can u give me a URL?

**Comment by shivsah** [comment]
@zackmark29 One of these days, I'll actually manage to get it from you..

BTW.. just a question.. Did you actually got the url of all the fragments and then merged it...

**Comment by shivsah** [comment]
> ~@zackmark29 I am removing ur comment. I don't want this repo to get in any trouble~
> It was removed before I got to it, lol
> 
> @shivsah That shouldn't happen. Can u give me a URL?

```
[debug] Command-line config: ['-F', '--username', 'PRIVATE', '--password', 'PRIVATE', '--add-header', 'x-viki-app-ver:6.0.0', '--add-header', 'x-viki-as-id: 100005a', '--add-header', 'x-client-user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36', '--sub-lang', 'en', '--sub-format', 'vtt', '--write-sub', 'https://www.viki.com/videos/1143296v-touch-your-heart-episode-1', '--allow-unplayable-formats', '--verbose']
WARNING: --fixup is ignored since --allow-unplayable-formats was given
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.02.15
[debug] Python version 3.7.3 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[viki] Logging in
[viki] 1143296v: Downloading video JSON
[viki] 1143296v: Downloading new video JSON to get subtitles
[viki] 1143296v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1143296v:
ID         EXT RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
---------- --- ---------- --- - ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
mpd-http-6 m4a audio only     |   57k https |                   mp4a.40.2  57k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-7 m4a audio only     |   73k https |                   mp4a.40.2  73k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-5 m4a audio only     |   89k https |                   mp4a.40.2  89k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-8 m4a audio only     |  200k https |                   mp4a.40.2 200k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-9 m4a audio only     |  200k https |                   mp4a.40.2 200k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-1 mp4 426x238    24  |  278k https | avc1.640015  278k                        DASH video, mp4_dash
mpd-http-2 mp4 640x360    24  |  515k https | avc1.64001E  515k                        DASH video, mp4_dash
mpd-http-3 mp4 852x480    24  |  808k https | avc1.64001E  808k                        DASH video, mp4_dash
```

**Comment by zackmark29** [comment]
> @zackmark29 One of these days, I'll actually manage to get it from you..
> 
> BTW.. just a question.. Did you actually got the url of all the fragments and then merged it...

haha it's not gonna happen =D

**Comment by shivsah** [comment]
> > @zackmark29 One of these days, I'll actually manage to get it from you..
> > BTW.. just a question.. Did you actually got the url of all the fragments and then merged it...
> 
> haha it's not gonna happen =D

Is it similar to the Viu approach..?

**Comment by zackmark29** [comment]
> ~@zackmark29 I am removing ur comment. I don't want this repo to get in any trouble~
> It was removed before I got to it, lol
> 
> @shivsah That shouldn't happen. Can u give me a URL?

haha then I post it again to give some info only

![image](https://user-images.githubusercontent.com/62680932/108376575-16bdac00-723e-11eb-9666-79049615aed0.png)

I know you can also find a way to do it. But it's not written in python it's written in C#

**Comment by shivsah** [comment]
> > ~@zackmark29 I am removing ur comment. I don't want this repo to get in any trouble~
> > It was removed before I got to it, lol
> > @shivsah That shouldn't happen. Can u give me a URL?
> 
> haha then I post it again to give some info only
> 
> ![image](https://user-images.githubusercontent.com/62680932/108376575-16bdac00-723e-11eb-9666-79049615aed0.png)
> 
> I know you can also find a way to do it. But it's not written in python it's written in C#

I already saved the image.. 😂😂

**Comment by zackmark29** [comment]
> @zackmark29 One of these days, I'll actually manage to get it from you..
> 
> BTW.. just a question.. Did you actually got the url of all the fragments and then merged it...

Are you asking me? Yeah I have mpd parser then merge all segments etc...
The direct url I think only 720p right?

**Comment by shivsah** [comment]
> > @zackmark29 One of these days, I'll actually manage to get it from you..
> > BTW.. just a question.. Did you actually got the url of all the fragments and then merged it...
> 
> Are you asking me? Yeah I have mpd parser then merge all segments etc...
> The direct url I think only 720p right?

I saw the image, the way i see it, you're first getting all the stream urls then saving them in a .txt file and then finally grabbing all of them and merging them in a file

**Comment by zackmark29** [comment]
haha I'm about to delete it also.

**Comment by shivsah** [comment]
> haha I'm about to delete it also.

Repo Owner is faster..

**Comment by pukkandan** [comment]
> you're first getting all the stream urls then saving them in a .txt file and then finally grabbing all of them and merging them in a file

youtube-dl also does the same

---

Please don't discuss breaking DRM here. I will be forced to lock this thread

**Comment by zackmark29** [comment]
> > > @zackmark29 One of these days, I'll actually manage to get it from you..
> > > BTW.. just a question.. Did you actually got the url of all the fragments and then merged it...
> > 
> > 
> > Are you asking me? Yeah I have mpd parser then merge all segments etc...
> > The direct url I think only 720p right?
> 
> I saw the image, the way i see it, you're first getting all the stream urls then saving them in a .txt file and then finally grabbing all of them and merging them in a file

Yeah I'm parsing all segments from MPD then save to txt file then merge them

**Comment by zackmark29** [comment]
> > you're first getting all the stream urls then saving them in a .txt file and then finally grabbing all of them and merging them in a file
> 
> youtube-dl also does the same
> 
> Please don't discuss breaking DRM here. I will be forced to lock this thread

Yeah already removed

**Comment by zackmark29** [comment]
> > you're first getting all the stream urls then saving them in a .txt file and then finally grabbing all of them and merging them in a file
> 
> youtube-dl also does the same
> 
> Please don't discuss breaking DRM here. I will be forced to lock this thread

Yes it does the same now. Before we can just get the direct link instead of segments

**Comment by pukkandan** [comment]
@shivsah I don't have an account, so here is what I see:

```
$ youtube-dlc -F --add-header "x-viki-app-ver:6.0.0" --add-header "x-viki-as-id: 100005a" --add-header "x-client-user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36" https://www.viki.com/videos/1143296v-touch-your-heart-episode-1 --allow-unplayable-formats
WARNING: --fixup is ignored since --allow-unplayable-formats was given
[viki] 1143296v: Downloading video JSON
[viki] 1143296v: Downloading new video JSON to get subtitles
[viki] 1143296v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
[info] Available formats for 1143296v:
ID         EXT RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
---------- --- ---------- --- - ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
mpd-http-6 m4a audio only     |   57k https |                   mp4a.40.2  57k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-7 m4a audio only     |   73k https |                   mp4a.40.2  73k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-5 m4a audio only     |   89k https |                   mp4a.40.2  89k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-8 m4a audio only     |  200k https |                   mp4a.40.2 200k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-9 m4a audio only     |  200k https |                   mp4a.40.2 200k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-1 mp4 426x238    24  |  278k https | avc1.640015  278k                        DASH video, mp4_dash
mpd-http-2 mp4 640x360    24  |  515k https | avc1.64001E  515k                        DASH video, mp4_dash
mpd-http-3 mp4 852x480    24  |  808k https | avc1.64001E  808k                        DASH video, mp4_dash

$ youtube-dlc -F --add-header "x-viki-app-ver:6.0.0" --add-header "x-viki-as-id: 100005a" --add-header "x-client-user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36" https://www.viki.com/videos/1143296v-touch-your-heart-episode-1
[viki] 1143296v: Downloading video JSON
[viki] 1143296v: Downloading new video JSON to get subtitles
[viki] 1143296v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
[viki] 1143296v: Downloading video streams JSON
[viki] 1143296v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
[info] Available formats for 1143296v:
ID         EXT RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
---------- --- ---------- --- - ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
mpd-http-6 m4a audio only     |   49k https |                   mp4a.40.2  49k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-7 m4a audio only     |   65k https |                   mp4a.40.2  65k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-5 m4a audio only     |   81k https |                   mp4a.40.2  81k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-8 m4a audio only     |  193k https |                   mp4a.40.2 193k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-9 m4a audio only     |  193k https |                   mp4a.40.2 193k 48000Hz DASH audio, m4a_dash, 48000Hz
mpd-http-1 mp4 426x238    24  |  157k https | avc1.640015  157k                        DASH video, mp4_dash
mpd-http-2 mp4 640x360    24  |  298k https | avc1.64001E  298k                        DASH video, mp4_dash
```

Form this, it looks like `--allow-unplayable-formats` is working correctly

**Comment by shivsah** [comment]
@zackmark29 One question though is it MS Playready or Widevine

**Comment by zackmark29** [comment]
> @zackmark29 One question though is it MS Playready or Widevine

wv

**Comment by shivsah** [comment]
> > @zackmark29 One question though is it MS Playready or Widevine
> 
> wv

![image](https://user-images.githubusercontent.com/17703895/108393315-8715fe80-7239-11eb-8c26-0dcf1d9ca94b.png)
Done... 😂😂 Now I only need to find a way to automate it.. that WV is a big hint though
