### ISSUE TITLE
[Site Request] YouTube: Update the Invidious instances list

### ISSUE THREAD

**Issue by TheFrenchGhosty** [pukkandan/yt-dlp#92]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.02.16**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Copied from https://github.com/blackjack4494/yt-dlc/issues/179

The invidious instances list is heavily outdated, and include a lot of dead instances (while missing a lot of new ones).

https://github.com/pukkandan/yt-dlp/blob/master/youtube_dlc/extractor/youtube.py#L353

It would be nice if you could update it.

The list is here: https://github.com/iv-org/documentation/blob/master/Invidious-Instances.md

PS: it would be nice if you could also add the semi-private instance I maintain for some users: https://invidious.pussthecat.org

**Comment by pukkandan** [comment]
I am opposed to removing the dead instances unless youtube-dl does the same. But we can add the missing ones

Pls confirm that these are all the new ones:

```

                            (?:www\.)?invidious\.pussthecat\.org/|
                            (?:www\.)?invidious\.snopyta\.org/|
                            (?:www\.)?invidious\.048596\.xyz/|
                            (?:www\.)?invidious\.zee\.li/|
                            (?:www\.)?vid\.puffyan\.us/|
                            (?:(?:www|au)\.)?ytprivate\.com/|
                            (?:www\.)?invidious\.namazso\.eu/|
                            (?:www\.)?invidious\.ethibox\.fr/|
                            (?:www\.)?inv\.skyn3t\.in/|
                            (?:www\.)?invidious\.himiko\.cloud/|
                            (?:www\.)?w6ijuptxiku4xpnnaetxvnkc5vqcdu7mgns2u77qefoixi63vbvnpnqd\.onion/|
                            (?:www\.)?kbjggqkzv65ivcqj6bumvp337z6264huv5kpkwuv6gu5yjiskvan7fad\.onion/|
                            (?:www\.)?invidious\.3o7z6yfxhbw7n3za4rss6l434kmv55cgw2vuziwuigpwegswvwzqipyd\.onion/|
                            (?:www\.)?grwp24hodrefzvjjuccrkw3mjq4tzhaaq32amf33dzpmuxe7ilepcmad\.onion/|
```

**Comment by TheFrenchGhosty** [comment]
```(?:www\.)?invidious\.snopyta\.org/|```

Is already added as ```(?:(?:www|fi)\.)?invidious\.snopyta\.org/|``` however the "fi" subdomain isn't used anymore.

Otherwise, perfect!

**Comment by TheFrenchGhosty** [comment]
@pukkandan Thanks a lot for doing it so quickly! I truly hope this fork last, I already moved my [scripts](https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts) to it, so expect a lot of new users when I release 3.0.0.

**Comment by pukkandan** [comment]
@TheFrenchGhosty Off topic, I looked through your scripts and have a few suggestions.

In yt-dlp, that long format string is not required. The best format selection already prefers `res, fps, codec` in that order. Though, `vp9.2` and `vp9` are considered the same. Is there a significant advantage for using vp9.2 over vp9? If so, let me know and I'll make that the default

You can bypass the windows path length limit by using the prefix `\\?\`. So, `\\?\D:\...` for example. I'll also look into how this can be implemented directly in yt-dlp

**Comment by TheFrenchGhosty** [comment]
@pukkandan If you take a look at the Details.md document you will see that the script isn't just picking a specific resolution/fps/codec it picks a codec according to its quality (for example AVC is preferred for 240p-144p).

Even then, I'd rather keep it to have full control over it, and if one day I have to move to another fork that uses the youtube-dl format selection, I won't have to rewrite it.

From what I know VP9.2 is HDR only, however I might be wrong.

The path length limit isn't an issue anymore, I ended up dropping the Windows version in favor of WSL.

**Comment by pukkandan** [comment]
youtube-dl has also updated the list https://github.com/ytdl-org/youtube-dl/commit/9fc5eafb8e384453a49f7cfe73147be491f0b19d making https://github.com/pukkandan/yt-dlp/commit/c86d5023d0f300857e4dd65f129dbaa44385c740 obsolete

**Comment by pukkandan** [comment]
> From what I know VP9.2 is HDR only

So is there no HDR in the other codecs? in that case, it should be prefered even over avc1, no?

**Comment by TheFrenchGhosty** [comment]
@pukkandan av1 can be HDR too.

Everything should be preferred over AVC, except for 144p-240p

**Comment by TheFrenchGhosty** [comment]
>Edit: They just moved the code, didn't update the actual list

I don't expect them to ever update it. I won't even ask.
