### ISSUE TITLE
[Question] Live stream that recently ended downloading HLS despite filter `!is_live & !live`

### ISSUE THREAD

**Issue by jbruchon** [pukkandan/yt-dlp#98]
(This may not be a bug.) I'm on Windows. I don't want to download live streams via HLS ever, I want to skip any live stream that has not completely changed over to a standard YouTube video and download it on the next archive run, so I use `--match-filter "!is_live & !live"` to skip them. Despite that, a 2 hour live stream that ended less than 20 minutes before youtube-dl checked the channel (and presumably was still in DVR mode as a result) started doing an HLS download. I don't have debug output because the ffmpeg HLS download output slaughtered my scrollback.

My download command: `youtube-dl --match-filter "!is_live & !live" --cookies "%COOKIEFILE%" --add-metadata --write-description --write-info-json --write-thumbnail --download-archive "%DLARCHIVE%" --write-subs --write-auto-subs --sub-lang en,en_US --convert-subs srt -ciw -o "%%(title)s.%%(ext)s" -v %*`

**Comment by pukkandan** [comment]
The video isn't live, so `!is_live` passes. I don't remember there being a field called `live`. I am not on a PC rn. Will confirm when I am

**Comment by pukkandan** [comment]
I have checked the source and indeed `live` is not a field that exists in any extractor.

> I don't want to download live streams via HLS ever,

`-f (bv*+ba/b)[proto!^=m3u8]` should probably work. Give me a video URL to test

**Comment by jbruchon** [comment]
That's the hard part: I'd have to give you a live stream that ended *very* recently.

**Comment by pukkandan** [comment]
Here's a livestream that ended recently.
```
$ youtube-dlc.cmd iNGf7XYtU2Q -F
[youtube] iNGf7XYtU2Q: Downloading webpage
[youtube] iNGf7XYtU2Q: Downloading m3u8 information
[youtube] iNGf7XYtU2Q: Downloading MPD manifest
[info] Available formats for iNGf7XYtU2Q:
ID  EXT RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
--- --- ---------- --- - ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
139 m4a audio only     |   64k dash  |                   mp4a.40.5  64k 22050Hz DASH audio, m4a_dash, 22050Hz
140 m4a audio only     |  144k dash  |                   mp4a.40.2 144k 44100Hz DASH audio, m4a_dash, 44100Hz
160 mp4 256x144    30  |  124k dash  | avc1.42c00b  124k                        DASH video, mp4_dash
91  mp4 256x144    30  |  197k m3u8  | avc1.42c00b  197k mp4a.40.5   0k
133 mp4 426x240    30  |  258k dash  | avc1.4d4015  258k                        DASH video, mp4_dash
92  mp4 426x240    30  |  338k m3u8  | avc1.4d4015  338k mp4a.40.5   0k
134 mp4 640x360    30  |  646k dash  | avc1.4d401e  646k                        DASH video, mp4_dash
93  mp4 640x360    30  |  829k m3u8  | avc1.4d401e  829k mp4a.40.2   0k
135 mp4 854x480    30  | 1171k dash  | avc1.4d401f 1171k                        DASH video, mp4_dash
94  mp4 854x480    30  | 1380k m3u8  | avc1.4d401f 1380k mp4a.40.2   0k
136 mp4 1280x720   30  | 2326k dash  | avc1.4d401f 2326k                        DASH video, mp4_dash
95  mp4 1280x720   30  | 2593k m3u8  | avc1.4d401f 2593k mp4a.40.2   0k
137 mp4 1920x1080  30  | 4347k dash  | avc1.640028 4347k                        DASH video, mp4_dash
96  mp4 1920x1080  30  | 4715k m3u8  | avc1.640028 4715k mp4a.40.2   0k
```

If you don't wanna download the m3u8, I have confirmed that `-f "(bv*+ba/b)[protocol!^=m3u8]"` works.
If you don't want to download dash either, u can use `-f "(bv*+ba/b)[protocol!^=m3u8][protocol!*=dash]"`
